
export const manualsRoutes = [

  {
    name: 'EMERGENCIAS',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUAL DE EMERGENCIA COFC S.A R0/MANUAL DE EMERGENCIA BUQUES.pdf',
  },

  {
    name: 'MANTENIMIENTO',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUAL DE MANTENIMIENTO COCF ARGENTINA S.A R0/MGTMB COCF ARGENTINA S.A.    REVISION 0.pdf',
  },

  {
    name: 'OPERACIONES',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUAL DE OPERACIONES COFC S.A REVISION 0/MOB COFC ARGENTINA S.A.   REVISION 1.pdf',
  },

  {
    name: 'SEGURIDAD COMPAÑÍA',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUALES DE GESTION COMPAÑIA COCF ARGENTINA S.A.   REVISION 0/MGSC-REVISIÓN2.pdf',
  },

]