
export const manualsRoutes = [

  { 
    name: 'Persona-Designada', 
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/ACTA VISITA Persona Designada .docx'
  },
  
  {
    name: 'Cubierta-Máquinas',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FC-01 PLANILLA DE EQUIPOSVARIOS Y  CRITICOS CUBIERTA-MAQUINAS.xlsx',
  },
  
  {
    name: 'ZH9',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FC-101 CONTROL VENCIMIENTOS ZH9.xls',
  },
  
  {
    name: 'ZH10',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FC-101 CONTROL VENCIMIENTOS ZH10.xls',
  },
  
  {
    name: 'FP-101',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FORMULARIO FP-101.doc',
  },
  
  {
    name: 'FP-501',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FORMULARIO FP-501.doc',
  },
  
  {
    name: 'Reparación-Materiales',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FORMULARIO FS-106 PEDIDO REPARACION MATERIALES.doc',
  },
  
  {
    name: 'Recepción-Comando',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FORMULARIO PC-201 ENTREGA Y RECEPCION DE COMANDO.doc',
  },
  
  {
    name: 'Recepción-Comando-Máquinas',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FORMULARIO PC-201-1 ENTREGA Y RECEPCION DE COMANDO MAQUINAS.doc',
  },
  
  {
    name: 'Formularios-SGS',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FORMULARIOS DEL SGS.doc',
  },
  
  {
    name: 'SGS-Chino',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FP-101 POLITICAS EMPRESA  y FAMILIARIZACION SGS CHINO verificado.doc',
  },
  
  {
    name: 'SGS-Castellano',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FP-101 POLITICAS EMPRESA y FAMILIARIZACION SGS CASTELLANO.doc',
  },
  
  {
    name: 'Elementos-Chinos',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FP-502 ENTREGA ELEMENTOS CHINOS verificado.xls',
  },
  
  {
    name: 'Recibo-P.P',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FP-502 RECIBO ELEMENTOS P.P..xls',
  },
  
  {
    name: 'Alerta-Meteorológico',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FR-83 FORMULARIO ALERTA METEOROLOGICO.doc',
  },
  
  {
    name: 'Evaluación-Mitigación-Riesgos',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FR-701 Registro de la evaluación y Mitigación de riesgos.doc',
  },
  
  {
    name: 'Historial-Mantenimiento',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FS-106-01 HISTORIAL DE MANTENIMIENTO.docx',
  },
  
  {
    name: 'Buque-Retirado',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/FT 105-1 CONTROL BUQUE RETIRADO DE SERVICIO.xls',
  },
  
  {
    name: 'FA-112',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/MGC CAP. 11.1 Formulario Auditorìa FA-112.doc',
  },
  
  {
    name: 'FT-102-103-104',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/REG MAT. A27 FT-102,103,104.xlsx',
  },
  
  {
    name: 'Zafararnchos-Ejercicios',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/FORMULARIOS SGS COFC ARGENTINA SA R0/RZ-06 REG. ZAFARARNCHOS Y EJERCICIOS.doc',
  },
  
  {
    name: 'Poteros-Revisión-2',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/LISTA DE DOCUMENTACION ESPECIFICA REVISION 0/LDE COFC ARGENTINA S.A. POTEROS REVISION 2 .pdf',
  },
  
  {
    name: 'ZHOUYU-10',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUAL DE EMERGENCIA COFC S.A R0/ANEXO 1 ZHOU YU 10 - REMOLQUE DE EMERGENCIA-2023_compressed.pdf',
  },
  
  {
    name: 'ZHOUYU-9',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUAL DE EMERGENCIA COFC S.A R0/ANEXO 1 ZHOUYU 9 - REMOLQUE DE EMERGENCIA-2023_compressed.pdf',
  },
  
  {
    name: 'Emergencia-Buques',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUAL DE EMERGENCIA COFC S.A R0/MANUAL DE EMERGENCIA BUQUES.pdf',
  },
  
  {
    name: 'M.G.T. MANTENIMIENTO',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUAL DE MANTENIMIENTO COCF ARGENTINA S.A R0/MGTMB COCF ARGENTINA S.A.    REVISION 0.pdf',
  },
  
  {
    name: 'Revisión-1',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUAL DE OPERACIONES COFC S.A REVISION 0/MOB COFC ARGENTINA S.A.   REVISION 1.pdf',
  },
  
  {
    name: 'MGSC-2',
    route: 'SGS COFC ARGENTINA S.A OCTUBRE 2023 pdf/MANUALES DE GESTION COMPAÑIA COCF ARGENTINA S.A.   REVISION 0/MGSC-REVISIÓN2.pdf',
  },
  
]